name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v4

        - name: Cache
          id: cache-primes
          uses: actions/cache@v4
          with:
                path: ${{github.workspace}}/lib
                key: git-cache

        - name: git
          run: git submodule update

        - name: Configure CMake
          run: >
            cmake -B ${{github.workspace}}/build
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            -DCMAKE_CXX_COMPILER=cl
            -DCMAKE_C_COMPILER=cl

        - name: Build
          run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

        - name: ls
          run: tree /F ${{github.workspace}}/build/Release


        - name: result
          uses: actions/upload-artifact@v4
          with:
            name: exe
            path: ${{github.workspace}}/build/Release/cpp_story_painter.exe

